// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::B14:
			return "B14 Output";
		case Gpio::E12:
			return "Crank Input (E12)";
		case Gpio::E13:
			return "Cam Input (E13)";
		case Gpio::E14:
			return "Digital Input 3 (E14)";
		case Gpio::E15:
			return "Digital Input 4 (E15)";
		default:
			return nullptr;
	}
	return nullptr;
}