// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/iobox.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/trove8_j1.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/trove8_j2.yaml
#pragma once

#define PIN_1 EXTIOCHIP_0_IO_1
#define PIN_2 EXTIOCHIP_0_IO_2
#define PIN_3 EXTIOCHIP_0_IO_3
#define PIN_4 EXTIOCHIP_0_IO_4
#define PIN_5 EXTIOCHIP_0_IO_5
#define PIN_6 EXTIOCHIP_0_IO_6
#define PIN_7 EXTIOCHIP_0_IO_7
#define PIN_8 EXTIOCHIP_0_IO_8
#define PIN_9 EXTIOCHIP_0_IO_9
#define PIN_10 EXTIOCHIP_0_IO_10
#define PIN_11 EXTIOCHIP_0_IO_11
#define PIN_12 EXTIOCHIP_0_IO_12
#define PIN_13 EXTIOCHIP_0_IO_13
#define PIN_14 EXTIOCHIP_0_IO_14
#define PIN_15 EXTIOCHIP_0_IO_15
#define PIN_16 EXTIOCHIP_0_IO_16
