// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/trove8_j1.yaml
// auto-generated by PinoutLogic.java based on ../../../connectors/trove8_j2.yaml
#pragma once

