name: Update rusEFI Reference

on:
  schedule:
    - cron: '5 17 * * MON' # update rusEFI reference weekly on Mondays at 5:05 pm
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: rusefi/rusefi/.github/workflows/custom-board-update-rusefi-reference.yaml@master
    permissions:
      contents: write
